### ISSUE TITLE
Remove all other files that aren't the main game.

### ISSUE THREAD

**Issue by KilroyWasHere-cs-j** [AnthonyMundy/CrabAdventure#1]
You have files in this repo that don't seem to be for the main game, those should go. This is so the repo doesn't become so over crowed, but don't feel bad we all do I have a repo with like twenty useless files.

**Comment by AnthonyMundy** [comment]
Sorry, just started using. The one that is called (the most updated crab
game) in all caps is the one. There is probably a few errors, ngl. Should
be fixed soon.

**Comment by KilroyWasHere-cs-j** [comment]
Thanks.
I added some new issues to your repo. Check them out.

**Comment by AnthonyMundy** [comment]
Thx
