### ISSUE TITLE
Update files differently. I think this is what Eric means. 

### ISSUE THREAD

**Issue by KilroyWasHere-cs-j** [AnthonyMundy/CrabAdventure#2]
So when you push/upload a file to a Github rerpo you don't change the name of the file. When a file is uploaded to a repo Github automatically checks the file to be uploaded against the pre-existing file. So it looks for errors between the two.

**Comment by AnthonyMundy** [comment]
Oh cool. Thanks!

**Comment by KilroyWasHere-cs-j** [comment]
Also at the bottom of this thread next to the comment button is a button labeled "Close and Comment" press that to close this thread. Only do it when you've fixed the stated issue.
